package service;

public enum TransactionResult {
    SUCCESS,
    NOT_LOGGED_IN,
    HOUSE_NOT_FOUND,
    INVALID_DEAL_STATUS,
    SELF_PURCHASE_FORBIDDEN,
    SELF_RENT_FORBIDDEN,
    INSUFFICIENT_FUNDS,
    NOT_THE_OWNER,
    CONTRACT_NOT_FOUND,
    NOT_THE_TENANT,
    NOT_CANCELLABLE
}
